# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(blank=True, max_length=12)),
                ('image_product', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=254)),
                ('brand_name', models.CharField(blank=True, max_length=254)),
                ('model', models.CharField(blank=True, max_length=254)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('in_stock', models.CharField(blank=True, max_length=254)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('free_shipping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_apikey', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Subscriber'),
        ),
    ]
