# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='pwd',
        ),
    ]
